### ISSUE TITLE
this.$refs.modal.close() not removing body style="height: 100%; overflow: hidden;"

### ISSUE THREAD

**Issue by KristianTheodoreJabilles** [adeptoas/sweet-modal-vue#68] opened 2018-03-27 08:48 UTC
Hi,
I am using this.$refs.modal.close() to programatically close the modal.
It will close the modal but its not removing the body element style thats added when we open the modal.

Do you have any idea?

Thanks in advance.

**Comment by bluefirex** [comment] 2018-03-27 14:11
Duplicate of (or at least closely related to) https://github.com/adeptoas/sweet-modal-vue/issues/56

**Closed by bluefirex** 2018-03-27 14:11 UTC
Labels: duplicate
