### ISSUE TITLE
$refs property undefined when loaded via vue-router

### ISSUE THREAD

**Issue by dvatp** [adeptoas/sweet-modal-vue#9] opened 2017-04-05 14:38 UTC
I have an app consisting of several top-level components.  These are loaded by vue-router when the appropriate route is specified in the URI.  You can think of this as a simple SPA.

Each top-level component has a few sweet modals implemented as components.  In each modal component's template I create a "ref" attribute with a name like "attachment_delete" like this:
```
<template>
    <sweet-modal
        ref="attachment_delete"
        title="Delete Attachment?"
        icon="warning"
        blocking
        overlay-theme="dark"
        >Are you sure you want to delete this {{ typename }} attachment?
        <br>This action cannot be reverted.
        <button
            type="button"
            class="btn btn-success"
            slot="button"
            @click="onBtnCancelClick"
            ><span class="fa fa-arrow-left"></span> Cancel
        </button>
      </sweet-modal>
</template>
```
In the same modal component I have an event handler that listens for an event that says "open the delete attachment modal".  This handler then calls:

```
this.$refs.attachment_delete.open()
```

This works as expected if I navigate directly to the URI or if I reload the page (F5).  But when I click on my nav menu buttons, which use relative paths to cause vue-router to switch contexts and load the appropriate top-level component, the appropriate component loads correctly but none of my modals work anymore.  The error I get is:

```
Uncaught TypeError: Cannot read property 'open' of undefined
```

Printing out $refs in both the working and non-working cases reveals the problem.  In the working case I see the $refs object defined with:

```
attachment_delete: VueComponent
```

In the non-working case I see:
```
attachment_delete:  undefined
```

So the error is correct, but it's not clear to me why the ref property is present but not defined.  I suppose this could be a bug in vue-router, but this is the only context in which I can duplicate the problem so I figured I'd report here to get your feedback and then report to vue if necessary.

**Comment by bluefirex** [comment] 2017-04-08 20:59
When you switch pages in VueRouter, there are several callbacks being called when navigating to that component (see [Vue Lifecycle](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram)). It depends when you bind your event listener whether or not `$refs` has been created already or not.

For Example: created() doesn't have a DOM and therefore no `$refs`, yet, while mounted() has one.

This is not a bug specific to sweet-modal though so I'm going to close this issue but I'm open to help you.

**Closed by bluefirex** 2017-04-08 20:59 UTC
