### ISSUE TITLE
scrollbar issue

### ISSUE THREAD

**Issue by Chiyaoching** [adeptoas/sweet-modal-vue#49] opened 2017-11-15 06:02 UTC
version: > v1.1.2
description: when opened modal, the scrollbar will show just a few millisecond and then hide

**Comment by bluefirex** [comment] 2017-11-18 15:51
Duplicate of https://github.com/adeptoas/sweet-modal-vue/issues/46

**Closed by bluefirex** 2017-11-18 15:51 UTC
